Repository ros2/rmw_iceoryx, pull requests merged in 2022-01, with the labels that each got.

#70 Fix Python support by using C type support for message name lookup
  rmw_iceoryx_cpp/src/internal/iceoryx_name_conversion.cpp
  rmw_iceoryx_cpp/src/internal/iceoryx_type_info_introspection.cpp
Labels: bugfix

#72 Add gid support
  rmw_iceoryx_cpp/src/iceoryx_generate_gid.hpp
  rmw_iceoryx_cpp/src/internal/iceoryx_generate_gid.cpp
  rmw_iceoryx_cpp/src/rmw_compare_guids_equal.cpp
  rmw_iceoryx_cpp/src/rmw_get_gid_for_publisher.cpp
  rmw_iceoryx_cpp/src/types/iceoryx_publisher.hpp
Labels: refactoring

#73 Implement `rmw_qos_profile_check_compatible`
  rmw_iceoryx_cpp/src/rmw_qos.cpp
Labels: refactoring

#44 fix demo codes pod_loaded_msg by sample codes
  README.md
Labels: documentation

#74 Fix findings from #44
  README.md
Labels: documentation
